name: Deploy

on:
  push:
    tags:
      - 'latest'

jobs:
  extension_bundle:
    name: Extension Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create Release
      run: make pack
    - name: Upload Release
      uses: svenstaro/upload-release-action@2.11.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hotspot-toggle.zip
        tag: ${{ github.ref }}

